// ignore_for_file: constant_identifier_names

enum MenuHomeType {
  HOME,
  TRANSACTION,
  BANK_ACCOUNT,
  OPEN_BANK_MB_ACCOUNT,
  SCAN_QR,
  CREATE_QR,
  SCAN_CCCD,
  MERCHANT,
  SCAN_BANK,
  ADD_LINK_BANK_ACCOUNT,
  WALLET_QR,
  BUSINESS,
  INTRO_VIET_QR,
  SETTING,
  LOGOUT,
  OTHER,
}

enum SubMenuType { LIST_TRANSACTION, SALE_REPORT, OTHER }
